apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: flink-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "*"
    port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: false
