apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-applications/argocd.yaml
- argocd-applications/cert-manager.yaml
- argocd-applications/dex.yaml
- argocd-applications/istio-operator.yaml
- argocd-applications/kiali.yaml
