apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-applications/argocd.yaml
- argocd-applications/cert-manager.yaml
- argocd-applications/certificates.yaml
# Flink
- argocd-applications/spotify-flink-operator.yaml
# - argocd-applications/flink-operator.yaml
- argocd-applications/flink.yaml
# Istio
- argocd-applications/istio-operator.yaml
- argocd-applications/istio.yaml
- argocd-applications/istio-resources.yaml
