apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-applications/argocd.yaml
- argocd-applications/cert-manager.yaml
# Flink
- argocd-applications/flink-operator-crds.yaml
- argocd-applications/flink-operator-skip-crds.yaml
- argocd-applications/flink-system.yaml
# Istio
- argocd-applications/istio-operator.yaml
- argocd-applications/istio.yaml
- argocd-applications/istio-resources.yaml
