apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-operator-skip-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/haoxins/apache-flink-operator
    targetRevision: feat-helm-rbac
    path: helm/flink-operator
    helm:
      skipCrds: true
      parameters:
      - name: watchNamespaces[0]
        value: flink-system
      - name: image.repository
        value: asia.gcr.io/awx-cn-growth/apache-flink-operator
      - name: image.pullPolicy
        value: Always
      - name: rbac.namespaces[0]
        value: flink-system
      - name: rbac.namespaces[1]
        value: metric-job-operator
      # - name: webhook.create
      #   value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: flink-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
