apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-operator-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/haoxins/apache-flink-operator
    targetRevision: main
    path: helm/flink-kubernetes-operator
    helm:
      skipCrds: true
      parameters:
      - name: watchNamespaces[0]
        value: flink-system
      - name: image.repository
        value: ghcr.io/haoxins/apache-flink-operator
      - name: image.tag
        value: 6e1f0e8
      - name: image.pullPolicy
        value: Always
      # - name: webhook.create
      #   value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: flink-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
