apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/haoxins/poc-flink-k8s-native.git
    targetRevision: main
    path: flink
  destination:
    server: https://kubernetes.default.svc
    namespace: flink-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
