apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/haoxins/apache-flink-operator
    targetRevision: fix-com-name
    path: helm/flink-operator
    helm:
      parameters:
      - name: image.repository
        value: asia.gcr.io/awx-cn-growth/apache-flink-operator
      - name: image.pullPolicy
        value: Always
      - name: webhook.create
        value: false
  destination:
    server: https://kubernetes.default.svc
    namespace: flink-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
