apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio
spec:
  profile: default
  tag: 1.13.3
  hub: docker.io/istio
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    enablePrometheusMerge: false
    enableTracing: false
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 2
    # extensionProviders:
  components:
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      k8s:
        service:
          type: LoadBalancer
          externalTrafficPolicy: Local
    egressGateways:
    - enabled: false
      name: istio-egressgateway
  values:
    global:
      istiod:
        enableAnalysis: false
    sidecarInjectorWebhook:
      neverInjectSelector:
      - matchExpressions:
        - {key: app, operator: In, values: []}
    pilot:
      autoscaleEnabled: true
      autoscaleMax: 5
      autoscaleMin: 1
      configMap: true
      cpu:
        targetAverageUtilization: 80
      env:
        PILOT_ENABLE_STATUS: true
