apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metricjob-operator-flink-operator-role-binding
  namespace: flink-system
roleRef:
  kind: Role
  name: flink-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: metricjob-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metricjob-operator-flink-role-binding
  namespace: flink-system
roleRef:
  kind: Role
  name: flink
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: metricjob-operator
