apiVersion: flink.apache.org/v1alpha1
kind: FlinkDeployment
metadata:
  namespace: flink-system
  name: session-cluster-test
spec:
  image: flink:1.14.4
  flinkVersion: v1_14
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    replicas: 1
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
