apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  namespace: flink-system
  name: session-cluster-test
spec:
  image: flink:1.14
  flinkVersion: v1_14
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
  serviceAccount: flink
  jobManager:
    replicas: 2
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  # podTemplate:
  #   spec:
  #     serviceAccount: flink
  #     containers:
  #     - name: flink-main-container
  #       volumeMounts:
  #       - mountPath: /data/flink-system
  #         name: flink-system-data
  #     volumes:
  #     - name: flink-system-data
  #       persistentVolumeClaim:
  #         claimName: flink-system-claim
