apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-role
subjects:
- kind: ServiceAccount
  name: istio-system/istiod-service-account
