apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: test-1
spec:
  flinkVersion: "1.14"
  image:
    name: flink:1.14.3
    pullPolicy: Always
  jobManager:
    accessScope: Cluster
    securityContext:
      runAsUser: 9999
      runAsGroup: 9999
    ports:
      ui: 8081
    resources:
      limits:
        memory: 2048Mi
        cpu: 1000m
  taskManager:
    replicas: 1
    resources:
      limits:
        memory: 2048Mi
        cpu: 1000m
    volumes:
    - name: cache-volume
      emptyDir: {}
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
    sidecars:
    - name: sidecar
      image: alpine
      command:
      - sleep
      - "10000"
  envVars:
  flinkProperties:
    taskmanager.numberOfTaskSlots: "1"
