apiVersion: flink.apache.org/v1alpha1
kind: FlinkDeployment
metadata:
  namespace: flink-system
  name: session-cluster-a
spec:
  image: flink:1.14.3
  flinkVersion: v1_14
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: default # flink
  jobManager:
    replicas: 1
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
